AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  employeeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.gomezrondon.springrestawslambda.LambdaHandler::handleRequest'
      Runtime: java8
      CodeUri: ./build/libs/*-aws.jar
      Description: ''
      MemorySize: 256
      Timeout: 30
      Role: 'arn:aws:iam::<account number>:role/<lambda-role>'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
